version: '3.8'

services:
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#      args:
#        - NODE_ENV=production
#    ports:
#      - "3000:3000"
#    environment:
#      - NODE_ENV=production
#      - NEXT_PUBLIC_API_URL=https://api.flowershop.com
#    restart: always
#
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#      args:
#        - NODE_ENV=production
#    ports:
#      - "3001:3001"
#    volumes:
#      - ./backend/uploads:/app/uploads
#    environment:
#      - NODE_ENV=production
#      - PORT=3001
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_NAME=flower_shop
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - JWT_SECRET=${JWT_SECRET}
#    depends_on:
#      - postgres
#    restart: always

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flower_shop
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

volumes:
  postgres_data: 